### ISSUE TITLE
exception after scan: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by atommaki** [jenkinsci/grypescanner-plugin#9]
### Jenkins and plugins versions report

Jenkins: 2.426.1
OS: Linux - 5.15.0-89-generic
Java: 11.0.20.1 - Ubuntu (OpenJDK 64-Bit Server VM)
---
Office-365-Connector:4.20.2
active-directory:2.34
analysis-model-api:11.13.0
ansible:285.v2f044b_eb_7a_3e
ansicolor:1.0.4
ant:497.v94e7d9fffa_b_9
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.2.1-1.1
authentication-tokens:1.53.v1c90fd9191a_b_
bootstrap5-api:5.3.2-2
bouncycastle-api:2.29
branch-api:2.1135.v8de8e7899051
build-blocker-plugin:1.7.9
build-environment:1.7
build-monitor-plugin:1.14-745.ve2023a_305f40
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
cloud-stats:320.v96b_65297a_4b_b_
cloudbees-folder:6.858.v898218f3609d
code-coverage-api:4.99.0
command-launcher:107.v773860566e2e
commons-httpclient3-api:3.1-3
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-94.v3e1f4a_926e49
config-file-provider:959.vcff671a_4518b_
configurationslicing:548.ve92d48e66b_f8
copyartifact:722.v0662a_9b_e22a_c
coverage:1.4.0
credentials:1309.v8835d63eb_d8a_
credentials-binding:642.v737c34dea_6c2
cvs:2.19.1
data-tables-api:1.13.6-5
dependencyanalyzer:0.7
display-url-api:2.200.vb_9327d658781
docker-build-publish:1.4.0
docker-commons:439.va_3cb_0a_6a_fb_29
docker-java-api:3.3.1-79.v20b_53427e041
docker-plugin:1.5
docker-workflow:572.v950f58993843
dtkit-api:3.0.2
durable-task:523.va_a_22cf15d5e0
echarts-api:5.4.0-7
embeddable-build-status:412.v09da_db_1dee68
envinject:2.908.v66a_774b_31d93
envinject-api:1.199.v3ce31253ed13
external-monitor-job:215.v2e88e894db_f8
file-operations:177.vd1773063d935
font-awesome-api:6.4.2-1
forensics-api:2.3.0
git:5.2.1
git-client:4.5.0
git-server:99.va_0826a_b_cdfa_d
github:1.37.3.1
github-api:1.316-451.v15738eef3414
github-branch-source:1750.v6b_fb_8df8f985
github-pullrequest:0.5.0
gitlab-api:5.3.0-91.v1f9a_fda_d654f
gitlab-logo:1.1.2
gitlab-merge-request-jenkins:2.0.0
gitlab-oauth:1.18
gitlab-plugin:1.7.16
grypescanner:1.8
h2-api:11.1.4.199-12.v9f4244395f7a_
htmlpublisher:1.32
instance-identity:185.v303dc7c645f9
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.15.3-372.v309620682326
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:243.vb_b_503b_b_45537
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
jdk-tool:73.vddf737284550
jenkins-jira-plugin:3.10.0
jersey2-api:2.41-133.va_03323b_a_1396
jira:3.11
jjwt-api:0.11.5-77.v646c772fddb_0
job-import-plugin:3.6
jobConfigHistory:1229.v3039470161a_d
jobcopy-builder:1.5.0
jquery3-api:3.7.1-1
jsch:0.2.8-65.v052c39de79b_2
junit:1240.vf9529b_881428
ldap:711.vb_d1a_491714dc
locale:314.v22ce953dfe9e
lockable-resources:1185.v0c528656ce04
log-parser:2.3.1
m2release:0.16.4
mailer:463.vedf8358e006b_
mapdb-api:1.0.9-28.vf251ce40855d
matrix-auth:3.2.1
matrix-project:818.v7eb_e657db_924
maven-plugin:3.23
mina-sshd-api-common:2.11.0-86.v836f585d47fa_
mina-sshd-api-core:2.11.0-86.v836f585d47fa_
nodejs:1.6.1
nvm-wrapper:0.1.7
okhttp-api:4.11.0-157.v6852a_a_fa_ec11
openJDK-native-plugin:1.7
pam-auth:1.10
pipeline-build-step:516.v8ee60a_81c5b_9
pipeline-github-lib:42.v0739460cda_c4
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:689.veec561a_dee13
pipeline-input-step:477.v339683a_8d55e
pipeline-maven:1362.vee39a_d4b_02b_1
pipeline-maven-api:1362.vee39a_d4b_02b_1
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2151.ve32c9d209a_3f
pipeline-model-definition:2.2151.ve32c9d209a_3f
pipeline-model-extensions:2.2151.ve32c9d209a_3f
pipeline-rest-api:2.34
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2151.ve32c9d209a_3f
pipeline-stage-view:2.34
pipeline-utility-steps:2.16.0
plain-credentials:143.v1b_df8b_d3b_e48
plugin-usage-plugin:4.2
plugin-util-api:3.6.0
polarion:1.3
prism-api:1.29.0-8
publish-over:0.22
publish-over-ssh:1.25
resource-disposer:0.23
scm-api:683.vb_16722fb_b_80b_
script-security:1275.v23895f409fb_d
scriptler:334.v29792d5a_c058
simple-theme-plugin:176.v39740c03a_a_f5
snakeyaml-api:2.2-111.vc6598e30cc65
snyk-security-scanner:4.0.2
sonar:2.16.1
ssh-credentials:308.ve4497b_ccd8f4
ssh-slaves:2.916.vd17b_43357ce4
sshd:3.312.v1c601b_c83b_0e
structs:325.vcb_307d2a_2782
subversion:2.17.3
svn-release-mgr:1.2
text-finder:1.26
timestamper:1.26
token-macro:384.vf35b_f26814ec
trilead-api:2.84.v72119de229b_7
variant:60.v7290fc0eb_b_cd
versionnumber:1.11
warnings-ng:10.5.1
windows-slaves:1.8.1
workflow-aggregator:596.v8c21c963d92d
workflow-api:1283.v99c10937efcb_
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:3806.va_3a_6988277b_2
workflow-cps-global-lib:609.vd95673f149b_b
workflow-durable-task-step:1289.v4d3e7b_01546b_
workflow-job:1360.vc6700e3136f5
workflow-multibranch:756.v891d88f2cd46
workflow-scm-step:415.v434365564324
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:865.v43e78cc44e0d
ws-cleanup:0.45
xunit:3.1.3

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 22.04, Java 11, Latest Jenkins LTS

### Reproduction steps

I try to scan some syft output (json). In the logs the run looks OK, but still I get an exception. It may be a configuration issue, but at least the  logging should be imporved, it doesn't tell me anything.

The grype step:
```
grypeScan scanDest: "file:${fileName}", repName: 'grype-report.json', autoInstall: true
```

The recordIssues step in the post section:
```
            recordIssues(
                tools: [grype(pattern: 'grype-report.json')],
                aggregatingResults: true
                )
```

### Expected Results

Valid build or at least a better error message

### Actual Results

red build, exception in the log:
```
00:01:16  Running grype scan:.
00:01:17  Installing grype...
00:01:17  [nerability-scan_servername] $ sh /home/jenkins/jenkins/workspace/nerability-scan_servername/grypeTmpDir/install.sh -b /home/jenkins/jenkins/workspace/nerability-scan_servername/grypeTmpDir/
00:01:17  [info] checking github for the current release tag.
00:01:17  [info] fetching release script for tag='v0.73.3'.
00:01:17  [info] checking github for the current release tag.
00:01:18  [info] using release tag='v0.73.3' version='0.73.3' os='linux' arch='amd64'.
00:01:20  [info] installed /home/jenkins/jenkins/workspace/nerability-scan_servername/grypeTmpDir//grype.
00:01:20  [nerability-scan_servername] $ /home/jenkins/jenkins/workspace/nerability-scan_servername/grypeTmpDir/grype file:/home/jenkins/jenkins/workspace/nerability-scan_servername/syft-report-servername.json -o template -t /home/jenkins/jenkins/workspace/nerability-scan_servername/grypeTmpDir/default.tmpl --file /home/jenkins/jenkins/workspace/nerability-scan_servername/grype-report.json
00:01:37  First (backward compatibility) grype run return value: 0
00:01:37..
00:01:37  Grype second run, generating report for Warnings Next Generation Plugin.
00:01:37  [nerability-scan_servername] $ /home/jenkins/jenkins/workspace/nerability-scan_servername/grypeTmpDir/grype file:/home/jenkins/jenkins/workspace/nerability-scan_servername/syft-report-servername.json -o json --file /home/jenkins/jenkins/workspace/nerability-scan_servername/grype-report.json
00:01:38  Second grype run return value: 0
00:01:38  Archiving artifacts
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] recordIssues
00:01:39  [Grype] Skipping execution of recorder since overall result is 'FAILURE'
[Pipeline] archiveArtifacts
00:01:39  Archiving artifacts
00:01:39  Recording fingerprints
[Pipeline] archiveArtifacts
00:01:39  Archiving artifacts
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
00:01:39  
[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 96220e33-3df7-4d91-87e4-d03831321f28
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at io.jenkins.plugins.grypescanner.Finding.<init>(Finding.java:66)
	at io.jenkins.plugins.grypescanner.Findings.<init>(Findings.java:43)
	at io.jenkins.plugins.grypescanner.GrypeScannerStep.perform(GrypeScannerStep.java:118)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Finished: FAILURE
```

**Comment by atommaki** [comment]
The problem is somehow the file naming. The plugin uses the name `grype-report.json` to generate the file  for the warning plugin, so I can't use that filename. As soon as I changed the filename, the exception disappeared. Strange limitation, but anyway, the logging should be better.
